### ISSUE TITLE
[Fix] 전체공연보러가기버튼 클릭 시 여러번 push되는 문제

### ISSUE THREAD

**Issue by dlrjswns** [YAPP-Github/24th-App-Team-3-iOS#115]
### Describe

- 홈화면에 `전체공연보러가기`버튼을 클릭 시 2~3번 푸시되는 문제 발생

### To Reproduce

1. 홈화면에서 `전체공연보러가기` 버튼 클릭
2. 여러번 반복 시 중복화면이동 발생

### Expected behavior

- `전체공연보러가기`버튼을 클릭하면 단 한번 전체공연화면으로 이동

### Screenshots

https://github.com/user-attachments/assets/c1956d04-956f-473a-bff6-e70890df387b

```
 Device: [e.g. iPhone15 Pro Max]
 OS: [e.g. iOS 16]
```

**Comment by ChoiysApple** [comment]
제 예상엔 Rx tap에 throttle 안줘서 이벤트가 중복으로 가는 문제같아요
현재는 간헐적으로 발생하는데, 테스트 기간에 실제로 빈번히 발생하는지 테스트 결과 보고 수정하시죠

**Comment by dlrjswns** [comment]
> 제 예상엔 Rx tap에 throttle 안줘서 이벤트가 중복으로 가는 문제같아요 현재는 간헐적으로 발생하는데, 테스트 기간에 실제로 빈번히 발생하는지 테스트 결과 보고 수정하시죠

한번 이번에 아티스트구독, 알림리스트 끝내놓고 throttle적용해서 확인해보겠습니다 !! 로그찍어봤는데 버튼탭했을때만 onNext찍히긴하더라구요😭😭😭

**Comment by ChoiysApple** [comment]
> > 제 예상엔 Rx tap에 throttle 안줘서 이벤트가 중복으로 가는 문제같아요 현재는 간헐적으로 발생하는데, 테스트 기간에 실제로 빈번히 발생하는지 테스트 결과 보고 수정하시죠
> 
> 한번 이번에 아티스트구독, 알림리스트 끝내놓고 throttle적용해서 확인해보겠습니다 !! 로그찍어봤는데 버튼탭했을때만 onNext찍히긴하더라구요😭😭😭

버튼 탭 한번하면 onNext 한번만 나온다는 말이에요?

**Comment by dlrjswns** [comment]
> > > 제 예상엔 Rx tap에 throttle 안줘서 이벤트가 중복으로 가는 문제같아요 현재는 간헐적으로 발생하는데, 테스트 기간에 실제로 빈번히 발생하는지 테스트 결과 보고 수정하시죠
> > 
> > 
> > 한번 이번에 아티스트구독, 알림리스트 끝내놓고 throttle적용해서 확인해보겠습니다 !! 로그찍어봤는데 버튼탭했을때만 onNext찍히긴하더라구요😭😭😭
> 
> 버튼 탭 한번하면 onNext 한번만 나온다는 말이에요?

아 `전체공연보러가기`버튼 클릭하면 onNext 한번 혹은 2번 찍혀요 !!
저는 처음에 문제가 `전체공연보러가기`버튼클릭안해도 이벤트가 방출되는건줄 알았거든요 

대건님 말한것처럼 throttle적용해야할꺼같아보여요
