### ISSUE TITLE
[Feature] 로그인 유무에 따른 설정화면 메뉴 변경

### ISSUE THREAD

**Issue by dlrjswns** [YAPP-Github/24th-App-Team-3-iOS#199]
### Describe

**기존 로직**
- 로그인 시 `계정메뉴`클릭 시 `계정화면`이동
- 비로그인 시 `계정메뉴`클릭 시 `로그인바텀시트`표출

**변경할 로직**
- 로그인 시 `계정메뉴` 추가
- 비로그인 시 `계정메뉴` 삭제

|로그인 상태|비로그인 상태|
|:-:|:-:|
<img src="https://github.com/user-attachments/assets/ec45256c-12f2-4767-a02f-99e875c1720e" width="40%" alt="Image">|<img src="https://github.com/user-attachments/assets/83738fc1-fbba-46b6-9a2a-a0593443de0f" width="40%" alt="Image">

**Comment by ChoiysApple** [comment]
@dlrjswns 
나중에 다시 확인할때 이해하기 편하도록 스크린샷 하나쯤 첨부해주세요~

**Comment by dlrjswns** [comment]
@ChoiysApple 
넵 스크린샷 첨부하였습니다
