### ISSUE TITLE
[Feature] 홈 화면 UI개발

### ISSUE THREAD

**Issue by dlrjswns** [YAPP-Github/24th-App-Team-3-iOS#53]
### Describe
- 피그마 MasterView에 디자인된 홈 UI를 개발
- 각각 세부적인 로직은 이후 구현
- 상단 로고와 검색버튼에 관련된 스크롤 동작 구현

#### 홈 화면 상단 스크롤 영역 논의 결과
1. 상단 로고이미지는 항상 고정
2. 스크롤방향(scrollUp, scrollDown)에 따라 서치바 show/hide 
3. 하단 쿠팡 홈 화면 스크롤에 따른 서치바 레이아웃 참고
https://github.com/user-attachments/assets/732dd035-d9b8-4e25-b860-705ad13da2e8

#### 홈 화면관련 안드로이드와 협의한 점
- `장르구독하기`, `아티스트구독하기`, `상단 로고 서치바` UI만을 개발하기로 협의 
- `상단 로고 서치바`에 대한 스크롤 기능 포함
- iOS파트같은 경우 구독이외의 `홈 화면의 전체 UI`, `상단 로고 서치바` 스크롤 기능 개발하여 안드로이드 해당 파트인(오현석)님께 공유
<img width="119" alt="스크린샷 2024-07-10 오후 5 43 24" src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/39263235/6429d357-2d08-4302-8abe-0e8740113bc8">

### Reference
* [홈 화면 상단 스크롤 영역관련 스레드 링크](https://discord.com/channels/1241701172532744202/1260834862345228308/1260837330617368739)
* [피그마 홈UI관련 링크](https://www.figma.com/design/KezpnXlqYPKL39yfOAn4FJ/%EB%94%94%EC%9E%90%EC%9D%B8-%EC%9E%91%EC%97%85%EC%9A%A9?node-id=493-9317&t=V5G5YUX5wvTufneB-4)

**Comment by ChoiysApple** [comment]
@dlrjswns 
1. 팀원끼리 논의한 내용을 포함시키는건 좋지만, 그 내용이 들어갈 거라면 논의 결과를 요약해서 올리는게 맞다고 봅니다. 이 부분은 진우님이 리뷰해주실 때도 참고 불가능하고 / 저도 보기가 힘들어요
2. 저번에도 유선상으로 논의했지만, 안드로이드와 개발 진행상황 맞추기 위해 개발 범위를 조절했었습니다. 그 부분도 명시가 필요합니다

참고로 제가 이슈 만드는건 시간 소요가 크지 않아서, 같이 논의한 기능 티켓은 제가 만들어도 됩니당 ㅎㅎ

**Comment by dlrjswns** [comment]
> @dlrjswns
> 
> 1. 팀원끼리 논의한 내용을 포함시키는건 좋지만, 그 내용이 들어갈 거라면 논의 결과를 요약해서 올리는게 맞다고 봅니다. 이 부분은 진우님이 리뷰해주실 때도 참고 불가능하고 / 저도 보기가 힘들어요
> 2. 저번에도 유선상으로 논의했지만, 안드로이드와 개발 진행상황 맞추기 위해 개발 범위를 조절했었습니다. 그 부분도 명시가 필요합니다
> 
> 참고로 제가 이슈 만드는건 시간 소요가 크지 않아서, 같이 논의한 기능 티켓은 제가 만들어도 됩니당 ㅎㅎ
@ChoiysApple 
아 스크롤영역부분에 대해서 확실한 설명을 적어놓을게요 !! 그 홈 UI같은 경우는 현석님쪽에 공유는 되었는데 기존 제가 작업했던것처럼 홈 전체 UI와 스크롤기능부분을 PR로 올려놓도록 하겠습니다 !!
