### ISSUE TITLE
[Feature] 소셜로그인버튼 cornerRadius값 주기

### ISSUE THREAD

**Issue by dlrjswns** [YAPP-Github/24th-App-Team-3-iOS#60]
### Describe

<img src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/39263235/715906a1-c8b9-4872-9716-301ee3efb0a8" width="25%" alt="Image">

- 소셜로그인버튼에 cornerRadius값 2 적용
- UIButton.Configuration으로 코드가 변경되면서 cornerRadius에 대한 코드를 수정

### Reference
[쇼팟 소셜로그인화면 피그마 링크](https://www.figma.com/design/KezpnXlqYPKL39yfOAn4FJ/%EB%94%94%EC%9E%90%EC%9D%B8-%EC%9E%91%EC%97%85%EC%9A%A9?node-id=803-3733&t=uRXRv9OMpliVTTVE-4)

**Comment by ChoiysApple** [comment]
@dlrjswns 
이정도로 세세한 작업까지 이슈 안만드셔도 됩니다 😅
소셜 로그인 추가작업 하시면서 진행하는 작업같은데, 그냥 그쪽 PR에 작업 포함시키면 될 것 같네요. 

이 이슈는 닫겠습니다.

```
p.s. 이건 개발 자체가 잘못된거라 Feature가 아니라 Bug로 다셔야 합니다
```
