### ISSUE TITLE
[Refactor] UIButton.Configuration에 attribute적용을 위한 함수 구현

### ISSUE THREAD

**Issue by dlrjswns** [YAPP-Github/24th-App-Team-3-iOS#61]
### Describe

- UIButton.Configuration으로 구성된 버튼에서는 반드시 AttributedString을 이용해서 텍스트를 작성해야하기때문에 기존 UILabel+Extension에 구현된 attribute함수를 사용하기 까다로운 문제점 발생 
``` swift
private func configureLabelAttributedText() -> UILabel { 
        let setAttributedButtonLabel = UILabel().then {
            $0.setAttributedText(font: KRFont.self, string: Strings.homeSearchBarPlaceHolder)
        }
        return setAttributedButtonLabel
}
    
/// UIButton.Configuration에 사용될 AttributedString을 리턴하는 함수
private func getButtonAttributedString() -> AttributedString? {
        let labelWithAttributedText = configureLabelAttributedText()
        guard let attributedText = labelWithAttributedText.attributedText else { return nil }
        
        var attributedString = AttributedString(attributedText)
        attributedString.font = KRFont.B1_semibold
        return attributedString
}
```
- 기존 자간 및 줄높이 적용을 위해 UIButton.Configuration에 대한 중복코드 발생
- 이 로직에 대한 공통함수를 생성해 중복코드 개선

**Comment by ChoiysApple** [comment]
@dlrjswns 
1. 이 작업은 기존에 보여지는 부분을 유지하면서, 코드 재사용성을 개선하는 개발 내부 작업이기 때문에 `Feature` 보다는 `Refactoring` 입니다. 
2. 코드상에 해당 이슈가 있다는건 저도 인지하고 있어서 제가 추가 작업 하려던게 있습니다.
지금 PR중인 폰트 관련 작업때문에 만드신 것 같은데, 일단 그 PR에 포함시켜주세요.

**Comment by ChoiysApple** [comment]
아 그리고 함수 메서드명에 `get` 이나 `set`이 들어가는 네이밍은 일반적으로 지양되는 네이밍 방식입니다.
개인적으로는 해당 방식이 최선인 경우가 있다고 느끼긴 하는데, 그래도 남용되지 않게 조심해주세요

**Comment by dlrjswns** [comment]
> @dlrjswns
> 
> 1. 이 작업은 기존에 보여지는 부분을 유지하면서, 코드 재사용성을 개선하는 개발 내부 작업이기 때문에 `Feature` 보다는 `Refactoring` 입니다.
> 2. 코드상에 해당 이슈가 있다는건 저도 인지하고 있어서 제가 추가 작업 하려던게 있습니다.
>    지금 PR중인 폰트 관련 작업때문에 만드신 것 같은데, 일단 그 PR에 포함시켜주세요.

아 맞습니다, 일단은 기존에 했던 방식처럼 홈PR에서는 디폴트라벨에 attribute를 적용시키고 자간 및 줄높이를 적용하는 방식으로 코딩해놓겠습니다.

**Comment by dlrjswns** [comment]
> 아 그리고 함수 메서드명에 `get` 이나 `set`이 들어가는 네이밍은 일반적으로 지양되는 네이밍 방식입니다. 개인적으로는 해당 방식이 최선인 경우가 있다고 느끼긴 하는데, 그래도 남용되지 않게 조심해주세요

아 그 부분 인지하도록 하겠습니다, 처음 알게된 사실이였네요 감사합니다 👍

**Comment by ChoiysApple** [comment]
추후 다른 방식으로 리팩토링 예정(별도 이슈 생성 예정)되어 해당 이슈 종결
