### ISSUE TITLE
[Feature] reuseIdentifier 지정 코드 기능 추가

### ISSUE THREAD

**Issue by ChoiysApple** [YAPP-Github/24th-App-Team-3-iOS#70]
### Describe
- #46 에서 진행한 작업의 기능 추가 작업
- `UICollectionViewCell`에 대한 메서드만 추가되어,  헤더나 푸터 관련 코드에는 동일한 형식의 코드 사용 불가

### Additional context
- 해당 작업 이후 #62 브랜치에서 해당 작업 내용을 끌어와 작업 필요

**Comment by dlrjswns** [comment]
확인했습니다 ! 이 부분 완료해주시면 수정하도록 할게요 👍

**Comment by ChoiysApple** [comment]
@dlrjswns 
건준님 코드 작업하려고 확인해 봤는데,

SupplementaryView를 dequeue할때는 타입.self를 사용하지 않아서 해당 방법 적용이 안될거 같은데요?

**Comment by dlrjswns** [comment]
> @dlrjswns 건준님 코드 작업하려고 확인해 봤는데,
> 
> SupplementaryView를 dequeue할때는 타입.self를 사용하지 않아서 해당 방법 적용이 안될거 같은데요?

흠 그러네요 ㅋㅋㅋㅋㅋㅋㅋ register에만 적용하는건 조금 비효율적일까요?

**Comment by ChoiysApple** [comment]
> > @dlrjswns 건준님 코드 작업하려고 확인해 봤는데,
> > SupplementaryView를 dequeue할때는 타입.self를 사용하지 않아서 해당 방법 적용이 안될거 같은데요?
> 
> 흠 그러네요 ㅋㅋㅋㅋㅋㅋㅋ register에만 적용하는건 조금 비효율적일까요?

아쉽지만 register에만 적용해서 올려드릴게요 ㅎㅎ
