### ISSUE TITLE
[Fix] develop브랜치 패키지 오류 발생

### ISSUE THREAD

**Issue by dlrjswns** [YAPP-Github/24th-App-Team-3-iOS#88]
### Describe

- develop브랜치를 최신화한 이후 "Missing package product" 에러로 빌드 실패

### To Reproduce

1. develop브랜치 pull 이후 체크아웃 
2. command + b 빌드 시도

### Expected behavior

- 빌드 오류없이 성공적으로 빌드되어야합니다

### Screenshots

<img width="833" alt="스크린샷 2024-07-29 오전 3 03 47" src="https://github.com/user-attachments/assets/9dee41a7-02da-4de6-be27-c51d518c26c1">

**Comment by dlrjswns** [comment]
@ChoiysApple 
대건님 develop브랜치 최신화 이후 빌드할때에 위와 같은 이슈가 발생하여 확인부탁드립니다

**Comment by ChoiysApple** [comment]
@dlrjswns 
hotfix 필요한 부분이라 PR 없이 `develop`에 바로 푸시했습니다.
확인 후 close 처리해주세요

**Comment by dlrjswns** [comment]
<img width="398" alt="스크린샷 2024-07-29 오후 3 31 06" src="https://github.com/user-attachments/assets/6ce24ddb-8865-4c84-b9aa-3def0d78c1d7">

@ChoiysApple 
아직 이슈가 있는거같은데 대건님쪽에서 develop 빌드하면 에러가 안날까요 ??

**Comment by ChoiysApple** [comment]
> <img width="398" alt="스크린샷 2024-07-29 오후 3 31 06" src="https://github.com/user-attachments/assets/6ce24ddb-8865-4c84-b9aa-3def0d78c1d7">
> 
> 
> 
> @ChoiysApple 
> 
> 아직 이슈가 있는거같은데 대건님쪽에서 develop 빌드하면 에러가 안날까요 ??

Derive Data 삭제하고 빌드한건가요?

**Comment by dlrjswns** [comment]
> > <img alt="스크린샷 2024-07-29 오후 3 31 06" width="398" src="https://private-user-images.githubusercontent.com/39263235/352937348-6ce24ddb-8865-4c84-b9aa-3def0d78c1d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzY0MzgsIm5iZiI6MTcyMjIzNjEzOCwicGF0aCI6Ii8zOTI2MzIzNS8zNTI5MzczNDgtNmNlMjRkZGItODg2NS00Yzg0LWI5YWEtM2RlZjBkNzhjMWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA2NTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MTJhNTllNzBiODQwYzUzZGU5Zjk0OWE4ZDI3YTczMzIxOWU1M2NjMWE5Y2I5ZTA5MzM0NjQwN2RkMDgyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jPx0ijL8sa9vFbjG0LH_ukxCkTMqExJj2Bji3lPifkw">
> > @ChoiysApple
> > 아직 이슈가 있는거같은데 대건님쪽에서 develop 빌드하면 에러가 안날까요 ??
> 
> Derive Data 삭제 / 클린 빌드 완료하고 빌드한건가요?

아 Derive Data는 삭제안하고 클린빌드했어요
Derive Data는 전부 삭제하고 시도하면될까요 ?

**Comment by ChoiysApple** [comment]
@dlrjswns 
안되요?

**Comment by dlrjswns** [comment]
@ChoiysApple 
잠시만요 지금 막 진료가 끝나서 해보고 말씀드릴게요

**Comment by dlrjswns** [comment]
@ChoiysApple 
Derived Data를 삭제하고 클린빌드해도 안돼요

**Comment by dlrjswns** [comment]
> @ChoiysApple Derived Data를 삭제하고 클린빌드해도 안돼요
> 
> 데이터 삭제하고 Xcode 껏다 킨거죠?

@ChoiysApple 
아 이제 됐어요 아래꺼 참고하니까 성공했네요 
https://sujinnaljin.medium.com/xcode-deriveddata-%EC%82%AD%EC%A0%9C%ED%95%98%EA%B8%B0-b64492ecb4a7

**Comment by dlrjswns** [comment]
이 이슈는 해결됐으니 닫도록 하겠습니다
