### ISSUE TITLE
[Fix] SPLabel 텍스트 내려가보이는 문제

### ISSUE THREAD

**Issue by dlrjswns** [YAPP-Github/24th-App-Team-3-iOS#97]
### Describe

- `UILabel` -> `SPLabel`로 변경 후 기존 티켓팅 셀 시간에 관련된 텍스트가 중간에 위치하지않고 내려가보이는 문제

### To Reproduce

1. 홈화면 `PerformanceStateView`클래스 이동
2. `ticketingOpenTimeLabel`를 UILabel 혹은 SPLabel로 변경
3. 각각 변경됨에 따라 다른 텍스트 위치를 홈화면을 보며 확인

### Expected behavior

- 티켓팅 시간정보에 대한 텍스트가 올바르게 `Chip UI`의 centerY에 배치됩니다

### Screenshots

* `UILabel`을 사용할 때
<img src="https://github.com/user-attachments/assets/f4e0cd7d-80e4-49e3-a49e-c8bcaae9fdbc" width="25%" alt="Image">

* `SPLabel`을 사용할 때
<img src="https://github.com/user-attachments/assets/b30327c2-b4e6-49c9-b779-1d4d71f327d2" width="25%" alt="Image">
<img src="https://github.com/user-attachments/assets/5857717b-d20f-4b97-bd62-23eedee15214" width="25%" alt="Image">

```
 Device: [e.g. iPhoneSE 3세대]
 OS: [e.g. iOS 16]
```

**Comment by dlrjswns** [comment]
@ChoiysApple 
대건님 - #94 에서 rebase이후 SPLabel로 변경하는 도중에 위 스크린샷처럼 baseLineOffset문제인지 기존 보이는 텍스트보다 가라앉아보이는 이슈가 있는거같습니다 

일단 확인하실 수 있도록 작업한 부분은 푸시해놓도록 할테니 확인부탁드려요

**Comment by dlrjswns** [comment]
<img width="330" alt="스크린샷 2024-08-02 오전 2 27 06" src="https://github.com/user-attachments/assets/e5c09e23-7f4e-477d-a089-8c9942063ed5">

지금보니까 다른 UI에 보이는 텍스트도 가라앉아보이긴하네요

**Comment by ChoiysApple** [comment]
@dlrjswns 
건준님 혹시 건준님이 개발한 Label들 다 고정 Height 들어가있어요?

**Comment by dlrjswns** [comment]
> @dlrjswns 혹시 건준님이 개발한 Label들 다 고정 Height 들어가있어요?

아뇨 라벨에 대한 고정 높이는 안들어가있어요

**Comment by ChoiysApple** [comment]
> 아뇨 라벨에 대한 고정 높이는 안들어가있어요

🤦‍♂️
제가 작업할때 온보딩은 괜찮았는데, 온보딩 확인 한번만 해주세요

**Comment by dlrjswns** [comment]
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-08-02 at 14 30 50](https://github.com/user-attachments/assets/23959399-c07d-42e4-a275-17e40a42c681)
엇 뭐지 혹시 SE 3세대 버전도 확인해보셨나요 ?

**Comment by ChoiysApple** [comment]
아뇨 15 하고 미니만 했어요

그리고 배경색 넣어서 테스트하셔야될거 같은데요
저건 priority 설정 안되어서 짤리는 느낌인데요

저건 고치면 되는데 지금 문제는 폰트니까 배경색 넣어서 큰 화면 되는걸로 테스트해주세요

**Comment by dlrjswns** [comment]
![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-02 at 14 43 02](https://github.com/user-attachments/assets/de358c07-5920-462d-95d0-7a2cfb50837c)
@ChoiysApple 
살짝 가라앉는 느낌이 드는거같긴해요 🧐

**Comment by ChoiysApple** [comment]
예상 가는 문제점은 있는데, 그거 해보고 안되면 디자인쪽에 line height 안된다고 통보할게요

폰트때문에 지금 1주는 잡아먹고 있는데 안되면 버리는게 맞을거 같네요
